### ISSUE TITLE
NSE stock price scraper

### ISSUE THREAD

**Issue by pratik-choudhari** [DarshanDeshpande/Scrapera#1]
I would like to contribute an NSE scraper which will help scrape the following:
1. Nifty50 index value
2. Last traded price of a particular stock
3. All nifty50 stock prices

P.S. This repository is a Great initiative✨

**Comment by DarshanDeshpande** [comment]
Sure. Go ahead. Make sure to read and follow the contributing guidelines [here](https://github.com/DarshanDeshpande/Scrapera/blob/master/CONTRIBUTING.md)

**Comment by Ashish0804** [comment]
@pratik-choudhari Why write a separate scraper for NSE when yahoo finance already provides it?

**Comment by pratik-choudhari** [comment]
@Ashish0804 Does yahoo finance API provide indian stock prices? If so, could you name the library?

**Comment by Ashish0804** [comment]
> @Ashish0804 Does yahoo finance API provide indian stock prices? If so, could you name the library?

Yes YF does provide data for both NSE aswell as BSE.
https://finance.yahoo.com/quote/RELIANCE.NS?p=RELIANCE.NS&.tsrc=fin-srch

Here's the library mostly used for getting data from YF
https://pypi.org/project/yfinance/

AFAIK pandas can also download data from YF.

**Comment by pratik-choudhari** [comment]
@Ashish0804 If its from yahoo website we still need to scrape it right? and yfinance doesn't recognize indian stocks, I have tried it, it doesn't recognize `SBI` or its ticker `SBIN`

**Comment by Ashish0804** [comment]
> @Ashish0804 If its from yahoo website we still need to scrape it right? and yfinance doesn't recognize indian stocks, I have tried it, it doesn't recognize `SBI` or its ticker `SBIN`

for non us exchanges you have to provide it's name along with exchange name
so for sbi it is SBIN.NS

And you don't have to scrape it from website. the yfinance library does everything. It is also used by algo traders so if fairly robust.

Here's the code to scrape SBI aswell as the output.


> Python 3.7.7 (default, May  7 2020, 21:25:33) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import yfinance as yf
> >>> sbi = yf.Ticker("SBIN.NS")
> >>> hist = sbi.history(period="1day")
> >>> print(hist)
>              Open   High         Low       Close    Volume  Dividends  Stock Splits
> Date                                                                               
> 2021-01-22  295.5  298.0  282.399994  283.700012  44440810          0             0
> 2021-01-22  295.5  298.0  282.399994  283.700012  44435474          0             0
> >>>


Please let me know if i am missing or confusing something.

**Comment by pratik-choudhari** [comment]
Oh yeah, thats great. @DarshanDeshpande If you want, you can close this issue. No problem by my side.
