### ISSUE TITLE
List of available crawler on README.md

### ISSUE THREAD

**Issue by zychen423** [DarshanDeshpande/Scrapera#3]
Hi, 

First of all, thank you for initialize such a wonderful project!

As I am reading this repo, I found it will be convenient if I can see what crawler is implemented from README, instead of looking into codes.

Not sure if this will be a good idea at this time. Feel free to leave your comment or simply close it.

**Comment by DarshanDeshpande** [comment]
Yes the documentation needs work. I will update the README later today. Thanks for the feedback!

**Comment by DarshanDeshpande** [comment]
I have updated the README with links to all scrapers that this library offers and will add separate READMEs for all modules in the upcoming commits. I am closing this issue for now. Feel free to create a pull request if you have any additions to the documentation or the code 👍
