### ISSUE TITLE
Make Reddit scraper Asynchronous

### ISSUE THREAD

**Issue by pratik-choudhari** [DarshanDeshpande/Scrapera#6]
This update will include same functionality as previous version but the execution is a lot faster. Here are the results:

POSTS SCRAPED | NORMAL | ASYNC
--|--|--
20 | 123s | 33s
50 | 213s | 63s
100 | 375s | 143s
200 | 738s | 262s

With the file sizes remaining almost constant

**Comment by DarshanDeshpande** [comment]
Can you create a pull request for this? For better clarity ofcourse

**Comment by pratik-choudhari** [comment]
Yes, definitely
