### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [DarshanDeshpande/Scrapera#8]
## Description 

Hi @DarshanDeshpande 👋 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/Scrapera/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point in time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Missing Arguement in Function Call ([here](https://deepsource.io/gh/HarshCasper/Scrapera/issue/PYL-E1120/))
- Unnecessary Generator ([here](https://deepsource.io/gh/HarshCasper/Scrapera/issue/PTC-W0015/))
- `f-string` used without any expression ([here](https://deepsource.io/gh/HarshCasper/Scrapera/issue/PTC-W0027/))
- Detected subprocess popen call with shell equals True ([here](https://deepsource.io/gh/HarshCasper/Scrapera/issue/BAN-B602/))
- Bad Expect Order ([here](https://deepsource.io/gh/HarshCasper/Scrapera/issue/PYL-E0701/))

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you would like to integrate DeepSource to autofix some of the common occurring issues, I can help you set that up :)

**Comment by DarshanDeshpande** [comment]
Yes I know that some code cleaning is required.  This analysis seems interesting. We could use a tool like this for future proofing

**Comment by HarshCasper** [comment]
> Yes I know that some code cleaning is required. This analysis seems interesting. We could use a tool like this for future proofing

Hi @DarshanDeshpande 👋 

Shall I raise a PR for the same and provide some cleanup with the Autofix tool? It would be a good way to judge the efficiency of the tool.

**Comment by DarshanDeshpande** [comment]
Yes that sounds good

**Comment by DarshanDeshpande** [comment]
PR Merged. Closing this issue
